tasks:
  - init: |
      # Pull projector docker and build with IntelliJ Idea 2021.3 Community Edition
      git clone https://github.com/JetBrains/projector-docker.git /workspace/template-jetbrains-intellij-idea/projector-docker
      cd /workspace/template-jetbrains-intellij-idea/projector-docker
      ./clone-projector-core.sh
      ./build-container.sh projector-idea-c:2021.3.1 https://download.jetbrains.com/idea/ideaIC-2021.3.1.tar.gz
    command: |
      cd /workspace/template-jetbrains-intellij-idea
      sudo mkdir -p .jetbrains; sudo touch .jetbrains/.gitkeep; sudo chown -R 1000:1000 .jetbrains
      # Run community edition
      sudo docker run --rm -p 8887:8887 -u 1000:1000 -v /workspace/template-jetbrains-intellij-idea/.jetbrains:/home/projector-user -it projector-idea-c:2021.3.1
     
ports:
  - port: 8887
    visibility: private
    onOpen: open-browser



